import pandas as pd

data = {
    'source': [
        'Машины стали неотъемлемой частью современной жизни. Они окружают нас повсюду, от автомобилей, облегчающих перемещение, до сложных промышленных механизмов, обеспечивающих производство товаров. Развитие технологий позволило создать интеллектуальные машины, которые могут выполнять сложные задачи с минимальным участием человека. Это привело к значительным изменениям в различных отраслях, начиная от медицины и заканчивая сельским хозяйством. С одной стороны, автоматизация улучшает качество жизни, освобождая людей от рутинных задач. С другой стороны, она поднимает вопросы о будущем трудовой занятости и о том, как машины могут изменить общество в долгосрочной перспективе.',
        'Кофе — это не просто напиток, а целая культура, объединяющая людей по всему миру. Сотни миллионов людей начинают свой день с чашки кофе, наслаждаясь его ароматом и бодрящим эффектом. История кофе насчитывает многие века и охватывает множество стран, от Эфиопии, где, как считается, были открыты кофейные зерна, до Южной Америки, ставшей основным поставщиком кофе на мировой рынок. Сегодня существует огромное разнообразие сортов и способов приготовления кофе, от традиционного эспрессо до модных напитков вроде латте или капучино. Кофе стал неотъемлемой частью повседневной жизни, вдохновляя людей на творчество и общение, а также предлагая мгновения уединения и размышлений.',
        'Машинное обучение — это одна из самых перспективных областей современной науки и технологий. Оно представляет собой метод, при котором компьютеры обучаются на основе данных и опыта, чтобы делать предсказания или принимать решения без явного программирования. Основная идея заключается в том, чтобы разработать алгоритмы, которые могут анализировать большие объемы данных, находить закономерности и использовать их для выполнения задач, которые ранее были доступны только человеку. Сегодня машинное обучение находит применение в самых разных областях — от медицины, где оно помогает диагностировать заболевания, до финансов, где его используют для анализа рынков и управления рисками. Оно также лежит в основе многих популярных технологий, таких как голосовые помощники, системы рекомендаций и автономные автомобили. Несмотря на огромные достижения, машинное обучение сталкивается с рядом вызовов, таких как необходимость в больших объемах данных, проблемы с интерпретируемостью моделей и этические вопросы, связанные с их использованием. Тем не менее, потенциал этой технологии огромен, и она продолжает активно развиваться, формируя будущее многих отраслей.'
    ],
    'reference': [
        'Machines have become an integral part of modern life. They are everywhere around us, from cars that make it easier to get around to complex industrial machinery that enables the production of goods. Advances in technology have made it possible to create intelligent machines that can perform complex tasks with minimal human intervention. This has led to significant changes in various industries, from medicine to agriculture. On the one hand, automation improves the quality of life by freeing people from routine tasks. On the other hand, it raises questions about the future of employment and how machines can change society in the long term.',
        'Coffee is not just a drink, but a whole culture that unites people all over the world. Hundreds of millions of people start their day with a cup of coffee, enjoying its aroma and invigorating effect. The history of coffee goes back many centuries and covers many countries, from Ethiopia, where coffee beans are believed to have been discovered, to South America, which has become the main supplier of coffee to the world market. Today, there is a huge variety of types and methods of preparing coffee, from traditional espresso to trendy drinks like latte or cappuccino. Coffee has become an integral part of everyday life, inspiring people to be creative and social, as well as offering moments of solitude and reflection.',
        'Machine learning is one of the most promising areas of modern science and technology. It is a method in which computers learn from data and experience to make predictions or decisions without being explicitly programmed. The basic idea is to develop algorithms that can analyze large amounts of data, find patterns, and use them to perform tasks that were previously only possible for humans. Today, machine learning is used in a variety of fields, from medicine, where it helps diagnose diseases, to finance, where it is used to analyze markets and manage risks. It is also the basis of many popular technologies, such as voice assistants, recommendation systems, and autonomous cars. Despite its enormous achievements, machine learning faces a number of challenges, such as the need for large amounts of data, problems with the interpretability of models, and ethical issues associated with its use. However, the potential of this technology is enormous, and it continues to develop rapidly, shaping the future of many industries.'
    ],
    'machine_translation': [
        'Machines have become an integral part of modern life. They surround us everywhere, from cars that make transportation easier to complex industrial mechanisms that enable the production of goods. Technological advancements have led to the creation of intelligent machines capable of performing complex tasks with minimal human involvement. This has resulted in significant changes across various industries, from healthcare to agriculture. On the one hand, automation improves the quality of life by freeing people from routine tasks. On the other hand, it raises questions about the future of employment and how machines may reshape society in the long run.',
        'Coffee is not just a drink but a whole culture that brings people together around the world. Hundreds of millions of people start their day with a cup of coffee, enjoying its aroma and invigorating effect. The history of coffee spans many centuries and covers numerous countries, from Ethiopia, where coffee beans were first discovered, to South America, which has become the main supplier of coffee to the global market. Today, there is a vast variety of coffee types and preparation methods, from traditional espresso to trendy drinks like lattes or cappuccinos. Coffee has become an integral part of daily life, inspiring creativity and communication, as well as offering moments of solitude and reflection.',
        'Machine learning is one of the most promising fields in modern science and technology. It is a method by which computers learn from data and experience to make predictions or decisions without explicit programming. The main idea is to develop algorithms that can analyze large volumes of data, identify patterns, and use them to perform tasks that were previously only accessible to humans. Today, machine learning is applied in various fields—from medicine, where it helps diagnose diseases, to finance, where it is used for market analysis and risk management. It also underpins many popular technologies such as voice assistants, recommendation systems, and autonomous vehicles. Despite significant advancements, machine learning faces several challenges, such as the need for large amounts of data, issues with model interpretability, and ethical concerns related to its use. Nevertheless, the potential of this technology is vast, and it continues to evolve, shaping the future of many industries.'
    ]
}

df = pd.DataFrame(data)

df.to_csv('./data/texts.csv', index = False)